const fs = require('fs');
const path = require('path');

const seedsPath = path.join(__dirname, '..', 'serverSeeds.json');
const seeds = JSON.parse(fs.readFileSync(seedsPath, 'utf8'));

// Update Spec Templates with shortLabel
seeds.INITIAL_SPEC_TEMPLATES = [
  {
    id: 'tpl-cctv',
    name: 'CCTV Camera',
    categorySlug: 'cctv-cameras',
    fields: [
      { id: 'f-res', name: 'Resolution', key: 'resolution', type: 'enum', options: ['2MP (1080p)', '4MP (2K)', '5MP Super HD', '8MP (4K)'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Resolution', order: 1 },
      { id: 'f-form', name: 'Form Factor', key: 'form_factor', type: 'enum', options: ['Bullet', 'Dome', 'Turret', 'PTZ'], filterable: true, comparable: true, shortLabel: 'Form Factor', order: 2 },
      { id: 'f-nv', name: 'Night Vision', key: 'night_vision', type: 'enum', options: ['IR Night Vision (up to 20m)', 'IR Night Vision (up to 40m)', 'ColorVu 24/7 Full Color', 'Smart Hybrid Light'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Night Vision', order: 3 },
      { id: 'f-lens', name: 'Lens', key: 'lens', type: 'enum', options: ['2.8mm (Wide Angle)', '3.6mm (Standard)', '6mm (Long Range)', 'Motorized Varifocal'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Lens', order: 4 },
      { id: 'f-ip', name: 'Ingress Protection', key: 'ip_rating', type: 'enum', options: ['IP66 Weatherproof', 'IP67 Weatherproof', 'Indoor Use'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'IP Rating', order: 5 },
      { id: 'f-aud', name: 'Audio Support', key: 'audio_support', type: 'boolean', filterable: true, comparable: true, shortLabel: 'Audio Support', order: 6 }
    ]
  },
  {
    id: 'tpl-dvr',
    name: 'NVR / DVR Recorder',
    categorySlug: 'dvr-nvr-recorders',
    fields: [
      { id: 'f-ch', name: 'Channels', key: 'channels', type: 'enum', options: ['4 Channels', '8 Channels', '16 Channels', '32 Channels'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Channels', order: 1 },
      { id: 'f-tech', name: 'Technology', key: 'technology', type: 'enum', options: ['Turbo HD / HD-TVI', 'IP / NVR', 'Hybrid (AcuSense)'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Tech', order: 2 },
      { id: 'f-hdd', name: 'Max HDD Capacity', key: 'max_hdd_capacity', type: 'unit', unit: 'TB', filterable: false, comparable: true, showInHighlights: true, shortLabel: 'Max HDD', order: 3 },
      { id: 'f-comp', name: 'Compression', key: 'compression', type: 'text', filterable: false, comparable: true, showInHighlights: true, shortLabel: 'Codec', order: 4 }
    ]
  },
  {
    id: 'tpl-switch',
    name: 'Network Switch',
    categorySlug: 'network-switches',
    fields: [
      { id: 'f-ports', name: 'Port Count', key: 'port_count', type: 'enum', options: ['5 Ports', '8 Ports', '16 Ports', '24 Ports'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Ports', order: 1 },
      { id: 'f-poe', name: 'PoE Support', key: 'poe_support', type: 'boolean', filterable: true, comparable: true, showInHighlights: true, shortLabel: 'PoE Support', order: 2 },
      { id: 'f-poebudget', name: 'PoE Power Budget', key: 'poe_budget', type: 'unit', unit: 'W', filterable: false, comparable: true, showInHighlights: true, shortLabel: 'PoE Budget', order: 3 },
      { id: 'f-mgmt', name: 'Management', key: 'management_type', type: 'enum', options: ['Unmanaged', 'Smart Cloud Managed', 'L2/L3 Managed'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Management', order: 4 }
    ]
  },
  {
    id: 'tpl-wifi',
    name: 'Access Point & Wi-Fi',
    categorySlug: 'access-points-wifi',
    fields: [
      { id: 'f-wifistd', name: 'Wi-Fi Standard', key: 'wifi_standard', type: 'enum', options: ['Wi-Fi 5 (802.11ac)', 'Wi-Fi 6 (802.11ax)'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Wi-Fi Std', order: 1 },
      { id: 'f-speed', name: 'Throughput', key: 'max_speed', type: 'unit', unit: 'Mbps', filterable: false, comparable: true, showInHighlights: true, shortLabel: 'Throughput', order: 2 },
      { id: 'f-mount', name: 'Mounting', key: 'mount_type', type: 'enum', options: ['Ceiling / Wall Mount', 'Outdoor Pole Mount', 'Desktop'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Mount', order: 3 }
    ]
  },
  {
    id: 'tpl-biometric',
    name: 'Biometric & Access Control',
    categorySlug: 'biometrics-access-control',
    fields: [
      { id: 'f-bio', name: 'Biometric Type', key: 'biometric_type', type: 'enum', options: ['Face Recognition + Fingerprint', 'Fingerprint + RFID Card', 'RFID Only'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Biometric', order: 1 },
      { id: 'f-usercap', name: 'User Capacity', key: 'user_capacity', type: 'number', filterable: false, comparable: true, showInHighlights: true, shortLabel: 'User Cap', order: 2 },
      { id: 'f-conn', name: 'Connectivity', key: 'connectivity', type: 'enum', options: ['TCP/IP + Wi-Fi', 'TCP/IP + USB', 'Standalone'], filterable: true, comparable: true, showInHighlights: true, shortLabel: 'Connectivity', order: 3 }
    ]
  }
];

// Clean sample testimonials
seeds.INITIAL_TESTIMONIALS = [
  {
    id: 'test-1',
    clientName: 'Sample Customer 1',
    clientRole: 'Operations Lead',
    company: 'Commercial Distribution Facility',
    content: 'The 16-camera surveillance and structured Cat6 trunking were deployed cleanly according to specification.',
    rating: 5,
    city: 'Dhaka',
    sample: true,
    isDemo: true
  },
  {
    id: 'test-2',
    clientName: 'Sample Customer 2',
    clientRole: 'Site Administrator',
    company: 'Multi-Tenant Commercial Office',
    content: 'Biometric facial attendance terminals synchronized reliably with our central local network setup.',
    rating: 5,
    city: 'Dhaka',
    sample: true,
    isDemo: true
  },
  {
    id: 'test-3',
    clientName: 'Sample Customer 3',
    clientRole: 'Building Manager',
    company: 'Residential Apartment Society',
    content: 'Clear night vision coverage installed at main vehicle checkpoints and entry corridors with zero clutter.',
    rating: 5,
    city: 'Dhaka',
    sample: true,
    isDemo: true
  }
];

// Clean sample projects
seeds.INITIAL_PROJECTS = [
  {
    id: 'proj-1',
    title: 'Sample Installation 1 - Multi-Storey Corporate Deployment',
    slug: 'sample-corporate-installation-dhaka',
    description: 'Structured Cat6 network distribution and 32-channel IP surveillance with server rack termination.',
    category: 'Commercial Surveillance',
    image: '/images/products/hikvision-bullet.svg',
    sample: true,
    isDemo: true
  },
  {
    id: 'proj-2',
    title: 'Sample Installation 2 - Warehouse Logistics Hub',
    slug: 'sample-warehouse-logistics-dhaka',
    description: 'Perimeter 4K cameras with Smart Hybrid dual illumination and industrial PoE Gigabit switches.',
    category: 'Industrial Security',
    image: '/images/products/hikvision-bullet.svg',
    sample: true,
    isDemo: true
  },
  {
    id: 'proj-3',
    title: 'Sample Installation 3 - Residential Society Access Control',
    slug: 'sample-residential-access-dhaka',
    description: 'Biometric attendance terminals and vehicular barrier gate cameras with dedicated local recording.',
    category: 'Biometrics & Access',
    image: '/images/products/zkteco-biometric.svg',
    sample: true,
    isDemo: true
  }
];

// 32 Sample Products across 6 categories
const sampleProducts = [
  // 1-5: CCTV Cameras
  {
    id: 'prod-hik-irpf-2mp',
    name: 'Hikvision 2MP Outdoor Bullet Camera',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-2CE1AD0T-IRPF',
    sku: 'HIK-CAM-IRPF-2MP',
    category: 'CCTV Cameras',
    categoryId: 'cat-cctv',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-bullet.svg'],
    primaryImage: '/images/products/hikvision-bullet.svg',
    shortDescription: 'Reliable 1080p Full HD infrared bullet camera with Smart IR up to 20m and IP67 weather resistance.',
    description: 'The Hikvision DS-2CE1AD0T-IRPF is an industry-standard 2MP analog bullet surveillance camera engineered for residential gates, retail storefronts, and perimeter monitoring.',
    keyFeatures: ['2 MP high performance CMOS sensor (1920 × 1080)', 'Smart IR: up to 20 m infrared night vision distance', '4 in 1 video output (switchable TVI/AHD/CVI/CVBS)', 'IP67 dust and water resistance'],
    specifications: { resolution: '2MP (1080p)', form_factor: 'Bullet', night_vision: 'IR Night Vision (up to 20m)', lens: '3.6mm (Standard)', ip_rating: 'IP67 Weatherproof', audio_support: false },
    specs: {
      resolution: { label: 'Resolution', value: '2MP (1080p)', highlightValue: '2 MP', showInHighlights: true },
      night_vision: { label: 'Night Vision', value: 'IR Night Vision (up to 20m)', highlightValue: '20m IR', showInHighlights: true },
      ip_rating: { label: 'IP Rating', value: 'IP67 Weatherproof', highlightValue: 'IP67', showInHighlights: true },
      form_factor: { label: 'Form Factor', value: 'Bullet', highlightValue: 'Bullet', showInHighlights: true }
    },
    pricing: { regularPrice: 2450, salePrice: 2150, currency: 'BDT' },
    inventory: { available: 50, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isFeatured: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-hik-dome-2mp',
    name: 'Hikvision 2MP Indoor Dome Camera',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-2CE56D0T-IRPF',
    sku: 'HIK-CAM-DOME-2MP',
    category: 'CCTV Cameras',
    categoryId: 'cat-cctv',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-dome.svg'],
    primaryImage: '/images/products/hikvision-dome.svg',
    shortDescription: 'Compact ceiling-mount 1080p indoor dome camera with 20m Smart IR night vision.',
    description: 'Engineered for indoor retail spaces, corporate lobbies, and office corridors requiring discrete aesthetic ceiling mounting.',
    keyFeatures: ['2 MP Full HD dome sensor', '20m Smart IR illumination', 'Pan/Tilt 3-axis manual adjustment'],
    specifications: { resolution: '2MP (1080p)', form_factor: 'Dome', night_vision: 'IR Night Vision (up to 20m)', lens: '2.8mm (Wide Angle)', ip_rating: 'Indoor Use', audio_support: false },
    specs: {
      resolution: { label: 'Resolution', value: '2MP (1080p)', highlightValue: '2 MP', showInHighlights: true },
      night_vision: { label: 'Night Vision', value: 'IR Night Vision (up to 20m)', highlightValue: '20m IR', showInHighlights: true },
      form_factor: { label: 'Form Factor', value: 'Dome', highlightValue: 'Dome', showInHighlights: true }
    },
    pricing: { regularPrice: 2700, currency: 'BDT' },
    inventory: { available: 40, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-12T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-hik-color-2mp',
    name: 'Hikvision 2MP ColorVu Bullet Camera',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-2CE10DF0T-F',
    sku: 'HIK-CAM-COLOR-2MP',
    category: 'CCTV Cameras',
    categoryId: 'cat-cctv',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-bullet.svg'],
    primaryImage: '/images/products/hikvision-bullet.svg',
    shortDescription: '24/7 full color imaging with F1.0 super aperture and warm white supplementary light.',
    description: 'ColorVu technology delivers vivid 24/7 color video in total darkness with 20m warm white LED lighting.',
    keyFeatures: ['24/7 Full Color video', 'F1.0 Super Aperture', '20m Warm White LED Light', 'IP67 Weatherproof'],
    specifications: { resolution: '2MP (1080p)', form_factor: 'Bullet', night_vision: 'ColorVu 24/7 Full Color', lens: '2.8mm (Wide Angle)', ip_rating: 'IP67 Weatherproof', audio_support: false },
    specs: {
      resolution: { label: 'Resolution', value: '2MP (1080p)', highlightValue: '2 MP', showInHighlights: true },
      night_vision: { label: 'Night Vision', value: 'ColorVu 24/7 Full Color', highlightValue: '24/7 Color', showInHighlights: true },
      ip_rating: { label: 'IP Rating', value: 'IP67 Weatherproof', highlightValue: 'IP67', showInHighlights: true }
    },
    pricing: { regularPrice: 3400, salePrice: 2990, currency: 'BDT' },
    inventory: { available: 35, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isTrending: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-hik-4k-bullet',
    name: 'Hikvision 4K Smart Hybrid Light Bullet',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-2CE18U0T-LFS',
    sku: 'HIK-CAM-4K-LFS',
    category: 'CCTV Cameras',
    categoryId: 'cat-cctv',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-bullet.svg'],
    primaryImage: '/images/products/hikvision-bullet.svg',
    shortDescription: 'Ultra HD 4K 8MP resolution with dual intelligent lighting and built-in audio microphone.',
    description: 'Enterprise 4K Ultra HD analog bullet camera engineered for long-range perimeter coverage with dual illumination.',
    keyFeatures: ['8 MP 4K Ultra HD resolution (3840 × 2160)', 'Smart Hybrid Light 40m IR + 20m White Light', 'Built-in Audio Mic over Coaxial', 'IP67 all-metal housing'],
    specifications: { resolution: '8MP (4K)', form_factor: 'Bullet', night_vision: 'Smart Hybrid Light', lens: '3.6mm (Standard)', ip_rating: 'IP67 Weatherproof', audio_support: true },
    specs: {
      resolution: { label: 'Resolution', value: '8MP (4K)', highlightValue: '4K', showInHighlights: true },
      night_vision: { label: 'Night Vision', value: 'Smart Hybrid Light', highlightValue: '40m Hybrid', showInHighlights: true },
      ip_rating: { label: 'IP Rating', value: 'IP67 Weatherproof', highlightValue: 'IP67', showInHighlights: true },
      audio_support: { label: 'Audio Support', value: true, highlightValue: 'Built-in Mic', showInHighlights: true }
    },
    pricing: { regularPrice: 5600, currency: 'BDT' },
    inventory: { available: 20, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isNew: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-dahua-2mp-bullet',
    name: 'Dahua 2MP HDCVI Weatherproof Bullet',
    brand: 'Dahua Technology',
    brandId: 'b-dahua',
    modelNumber: 'DH-HAC-HFW1200TP',
    sku: 'DAH-CAM-1200TP',
    category: 'CCTV Cameras',
    categoryId: 'cat-cctv',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-bullet.svg'],
    primaryImage: '/images/products/hikvision-bullet.svg',
    shortDescription: '1080p Full HD HDCVI bullet camera with 30m Smart IR and IP67 protection.',
    description: 'Robust surveillance camera from Dahua engineered for dependable exterior video security under tropical weather conditions.',
    keyFeatures: ['2MP HDCVI camera (1920 × 1080)', '30m Smart IR distance', 'IP67 weather resistant'],
    specifications: { resolution: '2MP (1080p)', form_factor: 'Bullet', night_vision: 'IR Night Vision (up to 40m)', lens: '3.6mm (Standard)', ip_rating: 'IP67 Weatherproof', audio_support: false },
    specs: {
      resolution: { label: 'Resolution', value: '2MP (1080p)', highlightValue: '2 MP', showInHighlights: true },
      night_vision: { label: 'Night Vision', value: 'IR Night Vision (up to 40m)', highlightValue: '30m IR', showInHighlights: true },
      ip_rating: { label: 'IP Rating', value: 'IP67 Weatherproof', highlightValue: 'IP67', showInHighlights: true }
    },
    pricing: { regularPrice: 2650, currency: 'BDT' },
    inventory: { available: 30, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },

  // 6-10: Recorders & DVR
  {
    id: 'prod-hik-dvr-4ch',
    name: 'Hikvision 4-Channel Turbo HD DVR',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-7104HGHI-M1',
    sku: 'HIK-DVR-4CH-M1',
    category: 'Recorders',
    categoryId: 'cat-recorders',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-dvr.svg'],
    primaryImage: '/images/products/hikvision-dvr.svg',
    shortDescription: 'Compact 4-channel digital video recorder with H.265 Pro+ smart compression.',
    description: '4-channel Turbo HD DVR supporting 1080p lite recording, HDMI & VGA output, and encrypted cloud remote mobile viewing.',
    keyFeatures: ['4 Channels analog video input', 'H.265 Pro+ / H.265 compression', '1 SATA interface up to 4TB HDD', 'Hik-Connect mobile cloud P2P'],
    specifications: { channels: '4 Channels', technology: 'Turbo HD / HD-TVI', max_hdd_capacity: 4, compression: 'H.265 Pro+' },
    specs: {
      channels: { label: 'Channels', value: '4 Channels', highlightValue: '4 Channels', showInHighlights: true },
      technology: { label: 'Tech', value: 'Turbo HD / HD-TVI', highlightValue: 'Turbo HD', showInHighlights: true },
      max_hdd_capacity: { label: 'Max HDD', value: 4, unit: 'TB', highlightValue: '4 TB', showInHighlights: true }
    },
    pricing: { regularPrice: 5800, currency: 'BDT' },
    inventory: { available: 25, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isFeatured: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-05T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-hik-dvr-8ch',
    name: 'Hikvision 8-Channel Turbo HD DVR',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-7108HGHI-M1',
    sku: 'HIK-DVR-8CH-M1',
    category: 'Recorders',
    categoryId: 'cat-recorders',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-dvr.svg'],
    primaryImage: '/images/products/hikvision-dvr.svg',
    shortDescription: '8-channel digital video recorder with H.265 Pro+ compression and HDMI 1080p output.',
    description: 'Standard 8-channel commercial digital video recorder for offices, medium residences, and retail complexes.',
    keyFeatures: ['8 Channels analog video input', 'H.265 Pro+ compression', '1 SATA interface up to 6TB', 'Remote mobile P2P access'],
    specifications: { channels: '8 Channels', technology: 'Turbo HD / HD-TVI', max_hdd_capacity: 6, compression: 'H.265 Pro+' },
    specs: {
      channels: { label: 'Channels', value: '8 Channels', highlightValue: '8 Channels', showInHighlights: true },
      technology: { label: 'Tech', value: 'Turbo HD / HD-TVI', highlightValue: 'Turbo HD', showInHighlights: true },
      max_hdd_capacity: { label: 'Max HDD', value: 6, unit: 'TB', highlightValue: '6 TB', showInHighlights: true }
    },
    pricing: { regularPrice: 7800, currency: 'BDT' },
    inventory: { available: 20, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isNew: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-05T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-hik-dvr-16ch',
    name: 'Hikvision 16-Channel Turbo HD DVR',
    brand: 'Hikvision',
    brandId: 'b-hikvision',
    modelNumber: 'DS-7216HGHI-M1',
    sku: 'HIK-DVR-16CH-M1',
    category: 'Recorders',
    categoryId: 'cat-recorders',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-dvr.svg'],
    primaryImage: '/images/products/hikvision-dvr.svg',
    shortDescription: '16-channel commercial DVR recorder with H.265 Pro+ encoding and dual monitor output.',
    description: 'Enterprise 16-channel surveillance recorder for campuses, manufacturing sites, and large facilities.',
    keyFeatures: ['16 Channels BNC video input', 'H.265 Pro+ compression', '1 SATA interface up to 10TB HDD', 'Simultaneous HDMI and VGA output'],
    specifications: { channels: '16 Channels', technology: 'Turbo HD / HD-TVI', max_hdd_capacity: 10, compression: 'H.265 Pro+' },
    specs: {
      channels: { label: 'Channels', value: '16 Channels', highlightValue: '16 Channels', showInHighlights: true },
      technology: { label: 'Tech', value: 'Turbo HD / HD-TVI', highlightValue: 'Turbo HD', showInHighlights: true }
    },
    pricing: { regularPrice: 12500, currency: 'BDT' },
    inventory: { available: 15, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-dahua-xvr-8ch',
    name: 'Dahua 8-Channel WizSense AI XVR',
    brand: 'Dahua Technology',
    brandId: 'b-dahua',
    modelNumber: 'DH-XVR5108HS-I3',
    sku: 'DAH-XVR-8CH-I3',
    category: 'Recorders',
    categoryId: 'cat-recorders',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hikvision-dvr.svg'],
    primaryImage: '/images/products/hikvision-dvr.svg',
    shortDescription: '8-channel AI digital recorder with Perimeter Protection and SMD Plus smart motion detection.',
    description: 'WizSense 8-channel XVR with deep learning algorithms for human and vehicle classification, filtering false alarms.',
    keyFeatures: ['8 Channels 5M-N/1080p recording', 'SMD Plus AI Human & Vehicle classification', 'AI Perimeter Protection', '1 SATA up to 10TB'],
    specifications: { channels: '8 Channels', technology: 'Hybrid (AcuSense)', max_hdd_capacity: 10, compression: 'AI H.265+' },
    specs: {
      channels: { label: 'Channels', value: '8 Channels', highlightValue: '8 Channels', showInHighlights: true },
      technology: { label: 'Tech', value: 'Hybrid (AcuSense)', highlightValue: 'WizSense AI', showInHighlights: true }
    },
    pricing: { regularPrice: 9800, currency: 'BDT' },
    inventory: { available: 12, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isTrending: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-08T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },

  // 11-15: Access Control & Biometrics
  {
    id: 'prod-zkteco-mb20',
    name: 'ZKTeco MB20 Face & Fingerprint Time Attendance',
    brand: 'ZKTeco',
    brandId: 'b-zkteco',
    modelNumber: 'MB20',
    sku: 'ZKT-BIO-MB20',
    category: 'Access Control & Biometrics',
    categoryId: 'cat-access',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/zkteco-biometric.svg'],
    primaryImage: '/images/products/zkteco-biometric.svg',
    shortDescription: 'Multi-biometric identification terminal with visible light face recognition and optical fingerprint sensor.',
    description: 'Engineered for corporate offices, retail branches, and educational institutions with TCP/IP network synchronization.',
    keyFeatures: ['200 Face Capacity, 500 Fingerprint Capacity', '2.8-inch TFT Color Display Screen', 'TCP/IP and USB-Host Connectivity', 'Access control door lock relay interface'],
    specifications: { biometric_type: 'Face Recognition + Fingerprint', user_capacity: 500, connectivity: 'TCP/IP + USB' },
    specs: {
      biometric_type: { label: 'Biometric', value: 'Face Recognition + Fingerprint', highlightValue: 'Face & Finger', showInHighlights: true },
      user_capacity: { label: 'User Cap', value: 500, highlightValue: '500 Users', showInHighlights: true },
      connectivity: { label: 'Connectivity', value: 'TCP/IP + USB', highlightValue: 'TCP/IP + USB', showInHighlights: true }
    },
    pricing: { regularPrice: 9500, currency: 'BDT' },
    inventory: { available: 20, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isFeatured: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-08T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-zkteco-k40',
    name: 'ZKTeco K40 Fingerprint Access Control Terminal',
    brand: 'ZKTeco',
    brandId: 'b-zkteco',
    modelNumber: 'K40',
    sku: 'ZKT-BIO-K40',
    category: 'Access Control & Biometrics',
    categoryId: 'cat-access',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/zkteco-biometric.svg'],
    primaryImage: '/images/products/zkteco-biometric.svg',
    shortDescription: 'Dependable fingerprint time attendance terminal with built-in backup battery and RFID card reader.',
    description: 'Cost-effective biometric terminal featuring battery backup during power outages and electronic door lock relay output.',
    keyFeatures: ['1,000 Fingerprints, 1,000 RFID Cards', 'Built-in Backup Battery for 3-4 hours operation', 'TCP/IP and USB communication', 'Simple access control electronic lock relay'],
    specifications: { biometric_type: 'Fingerprint + RFID Card', user_capacity: 1000, connectivity: 'TCP/IP + USB' },
    specs: {
      biometric_type: { label: 'Biometric', value: 'Fingerprint + RFID Card', highlightValue: 'Finger + RFID', showInHighlights: true },
      user_capacity: { label: 'User Cap', value: 1000, highlightValue: '1000 Users', showInHighlights: true },
      connectivity: { label: 'Connectivity', value: 'TCP/IP + USB', highlightValue: 'TCP/IP + USB', showInHighlights: true }
    },
    pricing: { regularPrice: 7200, currency: 'BDT' },
    inventory: { available: 30, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-14T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-zkteco-speedface-v5l',
    name: 'ZKTeco SpeedFace-V5L Visible Light Face Terminal',
    brand: 'ZKTeco',
    brandId: 'b-zkteco',
    modelNumber: 'SpeedFace-V5L',
    sku: 'ZKT-BIO-V5L',
    category: 'Access Control & Biometrics',
    categoryId: 'cat-access',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/zkteco-biometric.svg'],
    primaryImage: '/images/products/zkteco-biometric.svg',
    shortDescription: 'High-speed AI facial recognition access control terminal with anti-spoofing algorithm.',
    description: 'Enterprise grade visible light facial recognition terminal with touchless verification from 2 meters distance.',
    keyFeatures: ['6,000 Face Capacity, 10,000 Fingerprint Capacity', '0.3-second high speed verification', 'TCP/IP + Wi-Fi communication', 'Anti-spoofing print and video detection'],
    specifications: { biometric_type: 'Face Recognition + Fingerprint', user_capacity: 6000, connectivity: 'TCP/IP + Wi-Fi' },
    specs: {
      biometric_type: { label: 'Biometric', value: 'Face Recognition + Fingerprint', highlightValue: 'Visible Light', showInHighlights: true },
      user_capacity: { label: 'User Cap', value: 6000, highlightValue: '6000 Users', showInHighlights: true },
      connectivity: { label: 'Connectivity', value: 'TCP/IP + Wi-Fi', highlightValue: 'Wi-Fi + IP', showInHighlights: true }
    },
    pricing: { regularPrice: 24500, currency: 'BDT' },
    inventory: { available: 8, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isNew: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-12T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-zkteco-em-lock',
    name: 'ZKTeco 280kg Electromagnetic Glass Door Lock',
    brand: 'ZKTeco',
    brandId: 'b-zkteco',
    modelNumber: 'AL-280',
    sku: 'ZKT-LOCK-280KG',
    category: 'Access Control & Biometrics',
    categoryId: 'cat-access',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hardware-accessory.svg'],
    primaryImage: '/images/products/hardware-accessory.svg',
    shortDescription: '600lbs / 280kg holding force magnetic door lock with LED indicator and fail-safe operation.',
    description: 'Commercial magnetic door lock for frameless glass doors and wooden office entrance partitions.',
    keyFeatures: ['280 kg holding force', '12V DC operation', 'Dual voltage surge protection', 'Fail-safe safety release'],
    specifications: { biometric_type: 'RFID Only', user_capacity: 0, connectivity: 'Standalone' },
    specs: {
      biometric_type: { label: 'Lock Type', value: 'Magnetic Lock', highlightValue: '280 kg Hold', showInHighlights: true }
    },
    pricing: { regularPrice: 3800, currency: 'BDT' },
    inventory: { available: 25, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-22T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },

  // 16-20: Network Switches
  {
    id: 'prod-ruijie-es205gc-p',
    name: 'Ruijie Reyee 5-Port Gigabit Smart Managed PoE Switch',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-ES205GC-P',
    sku: 'RUI-SW-5P-POE',
    category: 'Network Switches',
    categoryId: 'cat-networking',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-switch.svg'],
    primaryImage: '/images/products/ruijie-switch.svg',
    shortDescription: '5-Port gigabit smart switch with 4 PoE+ ports (54W budget) and Ruijie Cloud remote app management.',
    description: 'Designed specifically for IP surveillance camera and Wi-Fi access point distribution with automated loop prevention.',
    keyFeatures: ['5 Gigabit 10/100/1000M ports', '4 PoE+ ports with 54W budget', 'Ruijie Cloud mobile app management', 'IP Camera reboot control'],
    specifications: { port_count: '5 Ports', poe_support: true, poe_budget: 54, management_type: 'Smart Cloud Managed' },
    specs: {
      port_count: { label: 'Ports', value: '5 Ports', highlightValue: '5 Ports', showInHighlights: true },
      poe_support: { label: 'PoE Support', value: true, highlightValue: 'PoE+', showInHighlights: true },
      poe_budget: { label: 'PoE Budget', value: 54, unit: 'W', highlightValue: '54 W', showInHighlights: true },
      management_type: { label: 'Management', value: 'Smart Cloud Managed', highlightValue: 'Cloud Managed', showInHighlights: true }
    },
    pricing: { regularPrice: 4200, currency: 'BDT' },
    inventory: { available: 40, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-18T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-ruijie-es209gc-p',
    name: 'Ruijie Reyee 9-Port Gigabit Smart Managed PoE Switch',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-ES209GC-P',
    sku: 'RUI-SW-9P-POE',
    category: 'Network Switches',
    categoryId: 'cat-networking',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-switch.svg'],
    primaryImage: '/images/products/ruijie-switch.svg',
    shortDescription: '9-Port gigabit switch with 8 PoE+ ports (120W budget) and cloud network management.',
    description: 'High-density PoE gigabit distribution switch for 8-camera CCTV installations and high-traffic Wi-Fi deployments.',
    keyFeatures: ['9 Gigabit RJ45 Ports (8 PoE+ ports)', '120W Total PoE Power Budget', 'Cloud topology view and reboot control', '6kV surge protection'],
    specifications: { port_count: '8 Ports', poe_support: true, poe_budget: 120, management_type: 'Smart Cloud Managed' },
    specs: {
      port_count: { label: 'Ports', value: '8 Ports', highlightValue: '8 Ports', showInHighlights: true },
      poe_support: { label: 'PoE Support', value: true, highlightValue: 'PoE+', showInHighlights: true },
      poe_budget: { label: 'PoE Budget', value: 120, unit: 'W', highlightValue: '120 W', showInHighlights: true },
      management_type: { label: 'Management', value: 'Smart Cloud Managed', highlightValue: 'Cloud Managed', showInHighlights: true }
    },
    pricing: { regularPrice: 8900, currency: 'BDT' },
    inventory: { available: 25, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-25T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-ruijie-es216gc',
    name: 'Ruijie Reyee 16-Port Gigabit Smart Managed Switch',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-ES216GC',
    sku: 'RUI-SW-16P-GIG',
    category: 'Network Switches',
    categoryId: 'cat-networking',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-switch.svg'],
    primaryImage: '/images/products/ruijie-switch.svg',
    shortDescription: '16-Port unmanaged rack-mountable gigabit switch with all metal housing.',
    description: 'Dependable gigabit distribution switch engineered for high-throughput server and DVR video recording networks.',
    keyFeatures: ['16 Gigabit ports 10/100/1000M', '32 Gbps switching capacity', '19-inch rack mounting brackets included', 'Internal power supply'],
    specifications: { port_count: '16 Ports', poe_support: false, poe_budget: 0, management_type: 'Unmanaged' },
    specs: {
      port_count: { label: 'Ports', value: '16 Ports', highlightValue: '16 Ports', showInHighlights: true },
      management_type: { label: 'Management', value: 'Unmanaged', highlightValue: 'Unmanaged', showInHighlights: true }
    },
    pricing: { regularPrice: 9400, currency: 'BDT' },
    inventory: { available: 15, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isNew: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-09T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-enterprise-switch-req',
    name: 'Ruijie Reyee 24-Port Gigabit Smart Managed PoE Switch',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-ES224GC-P',
    sku: 'RUI-SW-24P-POE',
    category: 'Network Switches',
    categoryId: 'cat-networking',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-switch.svg'],
    primaryImage: '/images/products/ruijie-switch.svg',
    shortDescription: '24-Port gigabit PoE+ switch with 370W power budget and cloud network telemetry.',
    description: 'Enterprise rackmount PoE switch for large scale security camera installations requiring heavy wattage power distribution.',
    keyFeatures: ['24 Gigabit PoE+ Ports', '370W High PoE Power Budget', 'Cloud managed with remote port reboot', 'VLAN isolation support'],
    specifications: { port_count: '24 Ports', poe_support: true, poe_budget: 370, management_type: 'Smart Cloud Managed' },
    specs: {
      port_count: { label: 'Ports', value: '24 Ports', highlightValue: '24 Ports', showInHighlights: true },
      poe_support: { label: 'PoE Support', value: true, highlightValue: 'PoE+', showInHighlights: true },
      poe_budget: { label: 'PoE Budget', value: 370, unit: 'W', highlightValue: '370 W', showInHighlights: true }
    },
    pricing: { currency: 'BDT' },
    inventory: { available: 5, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-30T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },

  // 21-25: Access Points & Wi-Fi
  {
    id: 'prod-ruijie-rap2200e',
    name: 'Ruijie Reyee RG-RAP2200(E) Wi-Fi 5 Ceiling AP',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-RAP2200(E)',
    sku: 'RUI-AP-RAP2200E',
    category: 'Access Points & Wi-Fi',
    categoryId: 'cat-wifi',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-wifi.svg'],
    primaryImage: '/images/products/ruijie-wifi.svg',
    shortDescription: 'High-performance dual-band ceiling-mount access point supporting up to 110 active clients.',
    description: 'Enterprise grade Wi-Fi ceiling AP featuring dual gigabit LAN ports, 1267 Mbps combined throughput, and Ruijie Reyee Mesh self-organizing network.',
    keyFeatures: ['Dual-band 802.11ac Wave 2 (1267 Mbps)', 'Dual Gigabit Ethernet ports (PoE input supported)', 'Self-Organizing Network (SON) with cloud management', 'Supports up to 110 concurrent client connections'],
    specifications: { wifi_standard: 'Wi-Fi 5 (802.11ac)', max_speed: 1267, mount_type: 'Ceiling / Wall Mount' },
    specs: {
      wifi_standard: { label: 'Wi-Fi Std', value: 'Wi-Fi 5 (802.11ac)', highlightValue: 'Wi-Fi 5', showInHighlights: true },
      max_speed: { label: 'Throughput', value: 1267, unit: 'Mbps', highlightValue: '1267 Mbps', showInHighlights: true },
      mount_type: { label: 'Mount', value: 'Ceiling / Wall Mount', highlightValue: 'Ceiling AP', showInHighlights: true }
    },
    pricing: { regularPrice: 8200, currency: 'BDT' },
    inventory: { available: 30, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isFeatured: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-16T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-ruijie-rap2260g',
    name: 'Ruijie Reyee RG-RAP2260(G) Wi-Fi 6 Ceiling Access Point',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-RAP2260(G)',
    sku: 'RUI-AP-RAP2260G',
    category: 'Access Points & Wi-Fi',
    categoryId: 'cat-wifi',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-wifi.svg'],
    primaryImage: '/images/products/ruijie-wifi.svg',
    shortDescription: 'AX1800 next-generation Wi-Fi 6 ceiling AP with high concurrency and OFDMA performance.',
    description: 'High-density Wi-Fi 6 access point delivering up to 1775 Mbps throughput for modern corporate workspaces and lecture halls.',
    keyFeatures: ['Wi-Fi 6 AX1800 (1775 Mbps)', 'OFDMA and MU-MIMO technologies', 'Dual Gigabit Ethernet ports with 802.3at PoE', 'Up to 512 client capacity'],
    specifications: { wifi_standard: 'Wi-Fi 6 (802.11ax)', max_speed: 1775, mount_type: 'Ceiling / Wall Mount' },
    specs: {
      wifi_standard: { label: 'Wi-Fi Std', value: 'Wi-Fi 6 (802.11ax)', highlightValue: 'Wi-Fi 6', showInHighlights: true },
      max_speed: { label: 'Throughput', value: 1775, unit: 'Mbps', highlightValue: '1775 Mbps', showInHighlights: true }
    },
    pricing: { regularPrice: 12500, currency: 'BDT' },
    inventory: { available: 20, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isTrending: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-02T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-ruijie-rap1200f',
    name: 'Ruijie Reyee RG-RAP1200(F) Wall-Plate In-Wall AP',
    brand: 'Ruijie Reyee',
    brandId: 'b-ruijie',
    modelNumber: 'RG-RAP1200(F)',
    sku: 'RUI-AP-WALL-1200F',
    category: 'Access Points & Wi-Fi',
    categoryId: 'cat-wifi',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/ruijie-wifi.svg'],
    primaryImage: '/images/products/ruijie-wifi.svg',
    shortDescription: 'In-wall 86-type faceplate Wi-Fi AP for hotel guest rooms, executive offices, and residences.',
    description: 'Compact 86mm wall switch box form-factor AP with front-facing Ethernet pass-through and 1267 Mbps Wi-Fi.',
    keyFeatures: ['Standard 86-type wall box installation', 'Dual-band AC1300 Wi-Fi', 'Front RJ45 LAN port output', 'PoE 802.3af powered'],
    specifications: { wifi_standard: 'Wi-Fi 5 (802.11ac)', max_speed: 1267, mount_type: 'Ceiling / Wall Mount' },
    specs: {
      wifi_standard: { label: 'Wi-Fi Std', value: 'Wi-Fi 5 (802.11ac)', highlightValue: 'Wi-Fi 5', showInHighlights: true },
      mount_type: { label: 'Mount', value: 'Ceiling / Wall Mount', highlightValue: 'In-Wall AP', showInHighlights: true }
    },
    pricing: { regularPrice: 5400, currency: 'BDT' },
    inventory: { available: 25, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isNew: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-02-06T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },

  // 26-29: Surveillance Storage
  {
    id: 'prod-wd-purple-500gb',
    name: 'Western Digital Purple 500GB Surveillance HDD',
    brand: 'Western Digital',
    brandId: 'b-wd',
    modelNumber: 'WD05PURZ',
    sku: 'WD-HDD-500GB',
    category: 'Surveillance Storage',
    categoryId: 'cat-storage',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/surveillance-hdd.svg'],
    primaryImage: '/images/products/surveillance-hdd.svg',
    shortDescription: 'Surveillance-grade 3.5-inch hard drive engineered for 24/7 continuous video recording.',
    description: 'WD Purple hard disk drive featuring AllFrame technology to reduce video frame loss and improve playback reliability in 2 to 4 camera systems.',
    keyFeatures: ['500GB continuous write storage', 'AllFrame technology for reduced frame loss', 'Engineered for 24/7 reliability', '3-Year manufacturer warranty'],
    specifications: { capacity: '500GB', form_factor: '3.5 inch', interface: 'SATA 6Gb/s' },
    specs: {
      capacity: { label: 'Capacity', value: '500GB', highlightValue: '500 GB', showInHighlights: true }
    },
    pricing: { regularPrice: 3200, currency: 'BDT' },
    inventory: { available: 50, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-02T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-wd-purple-1tb',
    name: 'Western Digital Purple 1TB Surveillance HDD',
    brand: 'Western Digital',
    brandId: 'b-wd',
    modelNumber: 'WD10PURZ',
    sku: 'WD-HDD-1TB',
    category: 'Surveillance Storage',
    categoryId: 'cat-storage',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/surveillance-hdd.svg'],
    primaryImage: '/images/products/surveillance-hdd.svg',
    shortDescription: 'Surveillance-grade 1TB continuous write hard drive supporting up to 64 HD cameras.',
    description: 'WD Purple 1TB internal hard drive engineered for 24/7 high-temperature surveillance environments.',
    keyFeatures: ['1TB capacity', 'AllFrame 4K technology', 'Workload rating up to 180 TB/year', 'SATA 6 Gb/s interface'],
    specifications: { capacity: '1TB', form_factor: '3.5 inch', interface: 'SATA 6Gb/s' },
    specs: {
      capacity: { label: 'Capacity', value: '1TB', highlightValue: '1 TB', showInHighlights: true }
    },
    pricing: { regularPrice: 4800, currency: 'BDT' },
    inventory: { available: 40, status: 'in_stock' },
    unit: 'Piece',
    isPopular: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-04T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'prod-wd-purple-2tb',
    name: 'Western Digital Purple 2TB Surveillance HDD',
    brand: 'Western Digital',
    brandId: 'b-wd',
    modelNumber: 'WD20PURZ',
    sku: 'WD-HDD-2TB',
    category: 'Surveillance Storage',
    categoryId: 'cat-storage',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/surveillance-hdd.svg'],
    primaryImage: '/images/products/surveillance-hdd.svg',
    shortDescription: 'High capacity 2TB surveillance hard drive for 8 to 16 camera extended video retention.',
    description: 'Optimized for modern NVR and DVR installations with heavy daily surveillance stream writing requirements.',
    keyFeatures: ['2TB continuous write storage', 'AllFrame video optimization', 'Tarnish-resistant components', 'Up to 64 single-stream HD cameras'],
    specifications: { capacity: '2TB', form_factor: '3.5 inch', interface: 'SATA 6Gb/s' },
    specs: {
      capacity: { label: 'Capacity', value: '2TB', highlightValue: '2 TB', showInHighlights: true }
    },
    pricing: { regularPrice: 6900, currency: 'BDT' },
    inventory: { available: 30, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isTrending: true,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },

  // 30-32: Cables & Power Accessories
  {
    id: 'cable-cat6',
    name: 'Cat6 UTP Pure Copper Surveillance Cable (Per Meter)',
    brand: 'CamneX Pro',
    brandId: 'b-ruijie',
    modelNumber: 'CAT6-UTP-1M',
    sku: 'CAB-CAT6-1M',
    category: 'Cables & Accessories',
    categoryId: 'cat-cables',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hardware-accessory.svg'],
    primaryImage: '/images/products/hardware-accessory.svg',
    shortDescription: 'High-grade 23 AWG solid bare copper Cat6 network cable with low signal attenuation.',
    description: 'Certified 23AWG unshielded twisted pair copper cable engineered for high-bandwidth IP surveillance, Gigabit PoE, and Turbo HD video signals.',
    keyFeatures: ['23 AWG solid bare copper conductor', 'Gigabit speed up to 250 MHz', 'PVC flame retardant outer jacket', 'Meter marking on outer jacket'],
    specifications: { conductor: 'Solid Bare Copper', gauge: '23 AWG', bandwidth: '250 MHz' },
    specs: {
      conductor: { label: 'Conductor', value: 'Solid Bare Copper', highlightValue: 'Pure Copper', showInHighlights: true },
      gauge: { label: 'Gauge', value: '23 AWG', highlightValue: '23 AWG', showInHighlights: true }
    },
    pricing: { regularPrice: 45, currency: 'BDT' },
    inventory: { available: 5000, status: 'in_stock' },
    unit: 'Meter',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-01T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'acc-power',
    name: 'Centralized 12V Regulated DC Power Supply Unit (10A)',
    brand: 'CamneX Pro',
    brandId: 'b-hikvision',
    modelNumber: 'PSU-12V-10A',
    sku: 'ACC-PSU-10A',
    category: 'Cables & Accessories',
    categoryId: 'cat-cables',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hardware-accessory.svg'],
    primaryImage: '/images/products/hardware-accessory.svg',
    shortDescription: 'Central metal enclosure power supply unit with individual PTC fuse terminals for up to 9 cameras.',
    description: 'Centralized 12V 10A regulated power distribution box with lockable metal casing and individual output status LEDs.',
    keyFeatures: ['12V DC 10A total output', '9 individually fused channel outputs', 'Short circuit and overload protection', 'Lockable key metal enclosure'],
    specifications: { output_voltage: '12V DC', current: '10A', channels: 9 },
    specs: {
      output_voltage: { label: 'Output', value: '12V DC', highlightValue: '12V DC', showInHighlights: true },
      current: { label: 'Current', value: '10A', highlightValue: '10A Power', showInHighlights: true }
    },
    pricing: { regularPrice: 1800, currency: 'BDT' },
    inventory: { available: 40, status: 'in_stock' },
    unit: 'Piece',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-05T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  },
  {
    id: 'acc-balun',
    name: 'Passive HD Video Balun & DC Power Pigtails (Per Camera Kit)',
    brand: 'CamneX Pro',
    brandId: 'b-hikvision',
    modelNumber: 'BALUN-HD-KIT',
    sku: 'ACC-BALUN-KIT',
    category: 'Cables & Accessories',
    categoryId: 'cat-cables',
    productType: 'physical',
    status: 'active',
    websiteVisible: true,
    posAvailable: true,
    images: ['/images/products/hardware-accessory.svg'],
    primaryImage: '/images/products/hardware-accessory.svg',
    shortDescription: 'High-definition passive video transceiver pair supporting TVI, AHD, and CVI signals over UTP cable.',
    description: 'Gold-plated BNC connectors and tool-free push-pin terminal blocks for clear video transmission up to 250m.',
    keyFeatures: ['Compatible with HD-TVI, HD-CVI, AHD, and CVBS', 'Built-in transient suppression protection', 'Tool-free spring terminal connections', 'Up to 250m transmission distance'],
    specifications: { connector_type: 'BNC to Terminal', compatibility: 'TVI/CVI/AHD' },
    specs: {
      compatibility: { label: 'Standard', value: 'TVI/CVI/AHD', highlightValue: 'HD-TVI/AHD', showInHighlights: true }
    },
    pricing: { regularPrice: 250, currency: 'BDT' },
    inventory: { available: 200, status: 'in_stock' },
    unit: 'Set',
    isPopular: false,
    isDemo: true,
    sample: true,
    createdAt: '2026-01-05T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z'
  }
];

seeds.INITIAL_PRODUCTS = sampleProducts;

// Update package 2 to use prod-hik-color-2mp
seeds.INITIAL_PACKAGES.forEach(pkg => {
  if (pkg.id === 'pkg-cctv-4cam-color') {
    pkg.rules.forEach(r => {
      if (r.role === 'camera') {
        r.defaultModelId = 'prod-hik-color-2mp';
      }
    });
  }
});

fs.writeFileSync(seedsPath, JSON.stringify(seeds, null, 2));
console.log('Successfully written ' + sampleProducts.length + ' products and updated serverSeeds.json');
